name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          install.packages(c("rcmdcheck", "stringdist", "Hmisc", "testthat"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Check package
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-vignettes", "--no-build-vignettes"), build_args = c("--no-manual", "--no-build-vignettes"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
